### ISSUE TITLE
How stable is this plugin?

### ISSUE THREAD

**Issue by noblefw** [mattboy9921/SkipNight#30]
I see it's fairly new and I'm running the latest version of Paper. Is it stable?

**Comment by mattboy9921** [comment]
If you are saying the plugin is new, SkipNight's first release dates back to 2019 with non public builds being used since 2017. 

I'm not quite sure what you mean by stable. SkipNight should not throw any errors in your console and should simply just work. I run it on my servers with zero stability type issues.
